name          'gdsoperations-graphite'
version       '1.0.1'
author        'Government Digital Service'
license       'MIT'
summary       'Module to manage the Graphite monitoring tool'
source        'https://github.com/gds-operations/puppet-graphite'
project_page  'https://github.com/gds-operations/puppet-graphite'

dependency    'puppetlabs/stdlib', '>= 2.5.0'
dependency    'stankevich/python', '>= 1.2.0'
