name          'gdsoperations-graphite'
version       '0.2.0'
author        'Government Digital Service'
license       'MIT'
summary       'Module to manage the Graphite monitoring tool'
source        'https://github.com/gds-operations/puppet-graphite'
project_page  'https://github.com/gds-operations/puppet-graphite'
dependency    'puppetlabs/stdlib', '>= 2.5.0'
