#! /bin/sh
### BEGIN INIT INFO
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: carbon-cache init script
# Description:       carbon-cache init script
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

if [ ! -f /etc/sysconfig/carbon-cache ]; then
    exit 6
fi

. /etc/sysconfig/carbon-cache

PID=/var/run/carbon-cache.pid

exec="<%= @root_dir %>/bin/carbon-cache.py"

[ -e /etc/sysconfig/carbon-cache ] && . /etc/sysconfig/carbon-cache

lockfile=/var/lock/subsys/carbon-cache

start() {
    [ -d $GRAPHITE_CONF_DIR ] || exit 6
    [ -x $exec ] || exit 5
    echo -n $"Starting `basename $exec`: "
    daemon "$exec --pidfile=$PID start"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping `basename $exec`: "
    killproc -p $PID `basename $exec`
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

rh_status() {
    status -p $PID `basename $exec`
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart}"
        exit 2
esac
exit $?