#! /bin/sh
### BEGIN INIT INFO
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Graphite realtime graphing engine
# Description:       Graphite realtime graphing engine
# chkconfig: 2345 99 01
### END INIT INFO

. /etc/init.d/functions

if [ ! -f /etc/sysconfig/graphite-web ]; then
    exit 6
fi

. /etc/sysconfig/graphite-web

PID=/var/run/graphite-web.pid

# Name of executable daemon
NAME=gunicorn-graphite
DESC=gunicorn-graphite

# Path to Executable
DAEMON=<%= @root_dir %>/bin/gunicorn_django

# DAEMON_OPTS="--user=$USER --group=$GROUP --bind=$BIND --pid=$PID --workers=$WORKERS --name=$APP --preload --daemon"
DAEMON_OPTS="-b <%= @bind_address -%>:<%= @port %> -w2 --pid=$PID settings.py"

case "$1" in
  start)
        CD_TO_APP_DIR="cd $APP_ROOT"

        echo -n "Starting $DESC: "
        $CD_TO_APP_DIR && $DAEMON $DAEMON_OPTS >/opt/graphite/storage/log/webapp/initscript.log 2>&1 &
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        kill -QUIT `cat $PID`
        echo "$NAME."
        ;;
  restart)
        stop
        start
        ;;
  status)
        status -p $PID `basename $DAEMON`
        ;;
  *)
        echo "Usage: $NAME {start|stop|restart|status}" >&2
        exit 1
        ;;
esac

exit 0
